methods: main.c fcfs.c sstf.c scan.c cscan.c look.c clook.c \
	initialize.c doublyLinkedList.c terminalColors.c
	gcc -o a.out main.c fcfs.c sstf.c scan.c cscan.c look.c clook.c \
	initialize.c doublyLinkedList.c terminalColors.c -I.